"""create chatbot user and permission table

Revision ID: 02125f5148f4
Revises: 
Create Date: 2024-06-24 15:14:17.098119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02125f5148f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('alias', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_user_name'), 'chatbot_user', ['name'], unique=False)
    op.create_table('chatbot_user_project_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=60), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['chatbot_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_user_project_permission_project_id'), 'chatbot_user_project_permission', ['project_id'], unique=False)
    op.create_index(op.f('ix_chatbot_user_project_permission_project_name'), 'chatbot_user_project_permission', ['project_name'], unique=False)
    op.create_index(op.f('ix_chatbot_user_project_permission_user_id'), 'chatbot_user_project_permission', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatbot_user_project_permission_user_id'), table_name='chatbot_user_project_permission')
    op.drop_index(op.f('ix_chatbot_user_project_permission_project_name'), table_name='chatbot_user_project_permission')
    op.drop_index(op.f('ix_chatbot_user_project_permission_project_id'), table_name='chatbot_user_project_permission')
    op.drop_table('chatbot_user_project_permission')
    op.drop_index(op.f('ix_chatbot_user_name'), table_name='chatbot_user')
    op.drop_table('chatbot_user')
    # ### end Alembic commands ###
