[base]
port = 8081
reload = true
log_path = "./logs"


[database]
    [database.mysql]
    host = "127.0.0.1"
    port = 33061
    user = "root"
    password = 123456
    database = "spg_helpdesk_chatbot"
    charset = "utf8mb4"


